{
 "title": "Spring Boot Statistics & Endpoint Metrics",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).\nThis is a fork of dashboard 6756, fixed for Spring Boot 2.3 and support for Jetty instead of Tomcat along with scraping endpoints' metrics.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded_classes, instance)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{instance=\"$instance\"},application)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Sum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  { "title": "JVM Statistics - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "repeat": "memory_pool_nonheap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  { "title": "JVM Statistics - GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  { "title": "HikariCP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"metrics-api\", instance=\"172.17.0.1:8080\", job=\"metrics-api\", pool=\"HikariPool-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_seconds_sum{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=\"$instance\", application=\"$application\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  },
  {
   "title": "Hibernate Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transactions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "hibernate_transactions_total{application=\"$application\", instance=\"$instance\", result=\"success\"}"
      }
     ]
    },
    {
     "title": "Prepared Statements ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "hibernate_statements_total{application=\"$application\", instance=\"$instance\", status=\"prepared\"}",
       "legendFormat": "Statements"
      }
     ]
    },
    {
     "title": "Total optimistic locking failures",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "hibernate_optimistic_failures_total"
      }
     ]
    },
    {
     "title": "Total query executions",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "hibernate_query_executions_total"
      }
     ]
    },
    {
     "title": "Entity Manager / Session Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(hibernate_sessions_open_total{application=\"$application\", instance=\"$instance\"}[5m])  ",
       "legendFormat": "sessions_opened"
      },
      {
       "expr": "rate(hibernate_sessions_closed_total{application=\"$application\", instance=\"$instance\"}[5m])  ",
       "legendFormat": "sessions_closed"
      },
      {
       "expr": "rate(hibernate_flushes_total{application=\"$application\", instance=\"$instance\"}[5m])  ",
       "legendFormat": "flushes"
      }
     ]
    },
    {
     "title": "Entity Collection Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(hibernate_collections_loads_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "collections loaded"
      },
      {
       "expr": "rate(hibernate_collections_updates_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "collections updated"
      },
      {
       "expr": "rate(hibernate_collections_fetches_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "collection fetches"
      },
      {
       "expr": "rate(hibernate_collections_deletes_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "remove"
      },
      {
       "expr": "rate(hibernate_collections_recreates_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "recreates"
      }
     ]
    },
    {
     "title": "Entity Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(hibernate_collections_loads_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "entities loaded"
      },
      {
       "expr": "rate(hibernate_entities_updates_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "entities updated"
      },
      {
       "expr": "rate(hibernate_entities_fetches_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "entities fetched"
      },
      {
       "expr": "rate(hibernate_entities_deletes_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "entities removed"
      },
      {
       "expr": "rate(hibernate_entities_recreates_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "recreates"
      },
      {
       "expr": "rate(hibernate_entities_inserts_total{application=\"$application\", instance=\"$instance\"}[2m])",
       "legendFormat": "entities inserted"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{instance=\"$instance\", application=\"$application\", exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Jetty Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Threads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jetty_threads_config_max{instance=\"$instance\", application=\"$application\"}  "
      }
     ]
    },
    {
     "title": "Jetty Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jetty_threads_busy{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "busy "
      },
      {
       "expr": "jetty_threads_idle{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "jetty_threads_current{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "current"
      },
      {
       "expr": "jetty_threads_jobs{instance=\"$instance\", application=\"$application\"}",
       "legendFormat": "jobs"
      }
     ]
    },
    {
     "title": "Thread Config Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jetty_threads_config_min{instance=\"$instance\", application=\"$application\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"info\"}[5m])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"error\"}[5m])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"warn\"}[5m])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"debug\"}[5m])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{instance=\"$instance\", application=\"$application\", level=\"trace\"}[5m])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}